export const LANDING = '/';
export const SIGN_UP = '/signup';
export const SIGN_IN = '/signin';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const PASSWORD_FORGET = '/pw-forget';
export const COMMENT = '/comment/:id';
export const ADMIN = '/admin';
export const ADMIN_DETAILS = '/admin/:id';
export const READER = '/reader';
export const GENRE = '/genre';
export const AUTHOR = '/author';
export const BOOK ='/book';
export const PROFILE = '/profile/:id/:userid'
export const REVIEW = '/review/:bookid'
export const BOOKADMIN ='/bookabmin/boodadd';
export const AUTHORADMIN ='/authorAdmin/authorAdd';
export const POSTADMIN ='/postAdmin/postAdd';
export const USERADMIN ='/admin/user';
export const USERADMINDETAILS ='/admin/user/:id';
export const INFO='/info/:value' ;
export const APROFILE='/authprofile/:id/:user';